version: '3.9'

services:

  service-discovery:
    build: ./service-discovery
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8761:8761'

  gateway:
    build: ./gateway
    image: gateway:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8080:8080'

  patient-database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: patient_database
      POSTGRES_USER: patient_user
      POSTGRES_PASSWORD: patient_password
    ports:
      - '5100:5432'

  patient:
    build: ./patient
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8081:8081'
    depends_on:
      - patient-database

  seizure-database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: seizure_database
      POSTGRES_USER: seizure_user
      POSTGRES_PASSWORD: seizure_password
    ports:
      - '5200:5432'

  seizure:
    build: ./seizure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8082:8082'
    depends_on:
      - seizure-database

  treatment-database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: treatment_database
      POSTGRES_USER: treatment_user
      POSTGRES_PASSWORD: treatment_password
    ports:
      - '5300:5432'

  treatment:
    build: ./treatment
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8083:8083'
    depends_on:
      - treatment-database