apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
        - name: patient
          image: venjilin/patient:latest
          ports:
            - containerPort: 8081
        - name: patient-database
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: patient_database
            - name: POSTGRES_USER
              value: patient_user
            - name: POSTGRES_PASSWORD
              value: patient_password
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: patient
spec:
  selector:
    app: patient
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer

    