apiVersion: apps/v1
kind: Deployment
metadata:
  name: seizure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seizure
  template:
    metadata:
      labels:
        app: seizure
    spec:
      containers:
        - name: seizure
          image: venjilin/seizure:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          ports:
            - containerPort: 8082
        - name: seizure-database
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: seizure_database
            - name: POSTGRES_USER
              value: seizure_user
            - name: POSTGRES_PASSWORD
              value: seizure_password
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: seizure
spec:
  selector:
    app: seizure
  ports:
    - port: 80
      targetPort: 8082
  type: LoadBalancer

    