apiVersion: apps/v1
kind: Deployment
metadata:
  name: treatment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treatment
  template:
    metadata:
      labels:
        app: treatment
    spec:
      containers:
        - name: treatment
          image: venjilin/treatment:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          ports:
            - containerPort: 8083
        - name: treatment-database
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: treatment_database
            - name: POSTGRES_USER
              value: treatment_user
            - name: POSTGRES_PASSWORD
              value: treatment_password
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: treatment
spec:
  selector:
    app: treatment
  ports:
    - port: 80
      targetPort: 8083
  type: LoadBalancer

    