apiVersion: apps/v1
kind: Deployment
metadata:
  name: treatment-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treatment-database
  template:
    metadata:
      labels:
        app: treatment-database
    spec:
      containers:
        - name: treatment-database
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: treatment_database
            - name: POSTGRES_USER
              value: treatment_user
            - name: POSTGRES_PASSWORD
              value: treatment_password
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: treatment-database
spec:
  selector:
    app: treatment-database
  ports:
    - port: 5300
      targetPort: 5432

    